export const LIST_FRIENDS = 'LIST_FRIENDS';
export const RETRIEVE_FRIEND = 'RETRIEVE_FRIEND';
export const DESTROY_FRIEND = 'DESTROY_FRIEND';

export const FRIENDS_REQUEST = 'FRIENDS_REQUEST';
export const FRIENDS_SUCCESS = 'FRIENDS_SUCCESS';
export const FRIENDS_ERROR = 'FRIENDS_ERROR';
export const FRIEND_SUCCESS = 'FRIEND_SUCCESS';
export const FRIEND_ERROR = 'FRIEND_ERROR';
export const FRIENDS_SEARCH = 'FRIENDS_SEARCH';
